### ISSUE TITLE
mounting a little unclear

### ISSUE THREAD

**Issue by karismatic-megafauna** [ksespinola/react-redux-calculator#2]
I see the benefits in a larger application to break the mounting up like you have, but it might be clearer if it was hard coded, as that abstraction really only makes it more complicated at this level.

Possibly do the mounting in the way you have detailed currently in master in a separate branch labeled advanced mounting?

Looks awesome so far! this is the only thing that I could think of to make it clearer :100:

**Comment by kespinola** [comment]
https://github.com/ksespinola/react-redux-calculator/blob/master/src/index.js

Made it simpler.

**Comment by karismatic-megafauna** [comment]
Awesomeness!!!!
